import {
    START_GAME,
    END_GAME,
    GET_QUESTIONS,
    INCREASE_SCORE,
    INCREASE_CORRECT,
    INCREASE_INCORRECT,
    SET_FINISHED,
    startGame,
    endGame,
    getQuestions,
    increaseScore,
    increaseCorrect,
    increaseIncorrect,
    setFinished,
} from "./gameActions";

export {
    START_GAME,
    END_GAME,
    GET_QUESTIONS,
    INCREASE_SCORE,
    INCREASE_CORRECT,
    INCREASE_INCORRECT,
    SET_FINISHED,
    startGame,
    endGame,
    getQuestions,
    increaseScore,
    increaseCorrect,
    increaseIncorrect,
    setFinished,
};